surface.CreateFont("ModernCarDealer.Font.Main", {font = "Open Sans", size = 65, weight = 2000, shadow = false})
surface.CreateFont("ModernCarDealer.Font.LargeText", {font = "Open Sans", size = 60, weight = 500, shadow = false})
surface.CreateFont("ModernCarDealer.Font.Text", {font = "Open Sans", size = 30, weight = 500, shadow = false})
surface.CreateFont("ModernCarDealer.Font.MediumText", {font = "Open Sans", size = 25, weight = 500, shadow = false})
surface.CreateFont("ModernCarDealer.Font.BoldText", {font = "Open Sans", size = 30, weight = 2000, shadow = false})
surface.CreateFont("ModernCarDealer.Font.BoldTextSmall", {font = "Open Sans", size = 20, weight = 2000, shadow = false})
surface.CreateFont("ModernCarDealer.Font.Category", {font = "Open Sans", size = 25, weight = 2000, shadow = false})
surface.CreateFont("ModernCarDealer.Font.Small", {font = "Open Sans", size = 20, weight = 500, antialias = true})
